worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Reduz a exibição da versão do Nginx (Segurança)
    server_tokens off;

    # Define o upstream apontando para o nome do serviço no Compose
    upstream backend_api {
        # O Docker fará o balanceamento Round-Robin automático entre as réplicas
        server web:8000;
    }

    server {
        listen 80;
        server_name localhost;

        # Rota de Healthcheck
        location /health {
            proxy_pass http://backend_api/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Timeout curto para healthcheck
            proxy_connect_timeout 5s;
            proxy_read_timeout 5s;
        }

        # Rota principal da API
        location / {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}